### ISSUE TITLE
Homework 1

### ISSUE THREAD

**Issue by pistriak** [SG2005/HomeWork1#1]
1. Don't leave comments like this         //calculations;
2. Read java code convention and format your code accordingly; 
3. A lot of code duplicates;

**Comment by SG2005** [comment]
Переделал свой код, 
1. На счет комментарий все понял,
2. Сode conventions пересмотрел, вроде сделал все правильно, не считая того, что я не до конца понимаю как быть с строками, которые нужно перенести на другую строку, особенно если эта строка касается просто System.out.println(много текста в кавычках). Не очень красиво получается у меня. 
3. По максимуму попытался сократить код, с этим у меня особенно возникают проблемы. Попытался в одном цикле делать то, что делал в двух, return переделал. Надеюсь все норм на этот раз.
